class statisticClass {
	public:
	int riverSection;
	int cell;
	int date;
	double lengthCell;
	double lengthSection;
	int rout_area;
	double con;
	double con2;
	double flowVelocity;
	double flowTime;
	double load_total;
	double load_total_2;
	double load_up;
	double load_up_2;
	double load_acc;
	double load_acc_2;
	double Q_out;
	double Q_d;
	double Q_in;
	double Qx;
	int station_id;
	double measured;
	int flag_uncert;
	double measured_conductivity;
	int flag_uncert_conductivity;
	int GRDC;
	double calculated;
	double measured_load;
	int flag_uncert_load;
	double measured_discharge;
	double flag_uncert_discharge;
	void setValues() { // diese Werte erstmal als NODATA fur alle Zeilen, werden in get_Output() gefuellt
		station_id = -9999;
		measured = -9999;
		flag_uncert = -9999;
		measured_conductivity = -9999;
		flag_uncert_conductivity = -9999;
		GRDC = -9999;
		calculated = -9999;
		measured_load = -9999;
		flag_uncert_load = -9999;
		measured_discharge = -9999;
		flag_uncert_discharge = -9999;
	}
	void copyValues(statisticClass line) {
		riverSection = line.riverSection;
		cell = line.cell;
		date = line.date;
		lengthCell = line.lengthCell;
		lengthSection = line.lengthSection;
		rout_area = line.rout_area;
		con = line.con;
		con2 = line.con2;
		flowVelocity = line.flowVelocity;
		flowTime = line.flowTime;
		load_total = line.load_total;
		load_total_2 = line.load_total_2;
		load_up = line.load_up;
		load_up_2 = line.load_up_2;
		load_acc = line.load_acc;
		load_acc_2 = line.load_acc_2;
		Q_out = line.Q_out;
		Q_d = line.Q_d;
		Q_in = line.Q_in;
		Qx = line.Qx;
		station_id = line.station_id;
		measured = line.measured;
		flag_uncert = line.flag_uncert;
		measured_conductivity = line.measured_conductivity;
		flag_uncert_conductivity = line.flag_uncert_conductivity;
		GRDC = line.GRDC;
		calculated = line.calculated;
		measured_load = line.measured_load;
		flag_uncert_load = line.flag_uncert_load;
		measured_discharge = line.measured_discharge;
		flag_uncert_discharge = line.flag_uncert_discharge;
	}
};
